AllCops:
  DisabledByDefault: false
  TargetRubyVersion: 2.3
  Exclude:
    - db/migrate/*
    - db/schema.rb
    - bin/**/*
Rails:
  Enabled: true
Metrics/LineLength:
  Max: 80
Metrics/ClassLength:
  CountComments: false
  Max: 100
  Exclude:
    - test/**/*
Metrics/ClassLength:
  CountComments: false
  Max: 300
  Include:
    - test/**/*
Style/AsciiComments:
  Enabled: false
Style/StringLiteralsInInterpolation:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
